#!/usr/bin/sh
PROJECT="docutools"
pyver="3.7" # min version

git config user.email "g_kl_es_sing_er@gmx.de"
google_analytics_key="$(pass show google/analytics_key_blog 2>/dev/null)"
# for git changelog:
versioning=calver
#lit_prog_eval_match="on_demand" # we use locks
# list of '::' seperated words to fail when occurring in committed files:
blacklisted_words="$(pass show sensitive/axgkl)"
# for browser screenshots:
nodejs="source $HOME/miniconda3/etc/profile.d/conda.sh && conda activate nodejs && node"
browser="chromium-browser"
# mkdocs serve:
mkdocs_port=2222
mkdocs_path="$PROJECT"
# giving us make docs, make tests, .. -a activates venv:
source ./make -a
echo "sourced ./make"
