@startuml
participant "MainThread" as MainThread
[-[#888888]-> MainThread: 0
MainThread<-[#888888]-]: [[1.json?req{\n    "say_hello": " function run_lp_flow. locals.say_hello at 0x7f5074080c20"\n} test_flow]]
activate MainThread
[-[#888888]-> MainThread: 2e-05
MainThread<-[#888888]-]: [[2.json?req{\n    "allow_nan": true,\n    "check_circular": true,\n    "cls": null,\n    "default": null,\n    "ensure_ascii": true,\n    "indent": null,\n    "kw": ,\n    "obj": \n        "name": "joe"\n    ,\n    "separators": null,\n    "skipkeys": false,\n    "sort_keys": false\n} dumps (json)]]
activate MainThread
[-[#888888]-> MainThread: 4e-05
MainThread<-[#888888]-]: [[3.json?req{\n    "o": \n        "name": "joe"\n    ,\n    "self": " json.encoder.JSONEncoder object at 0x7f5076f44610"\n} encode (json.JSONEncoder)]]
activate MainThread
[-[#888888]-> MainThread: 6e-05
MainThread<-[#888888]-]: [[4.json?req{\n    "_one_shot": true,\n    "o": \n        "name": "joe"\n    ,\n    "self": " json.encoder.JSONEncoder object at 0x7f5076f44610"\n} iterencode (json.JSONEncoder)]]
activate MainThread
deactivate MainThread
deactivate MainThread
deactivate MainThread
deactivate MainThread
@enduml