skinparam shadowing false
skinparam backgroundcolor transparent
skinparam DefaultFontName Arial
skinparam ArrowColor #00b2e2
skinparam DefaultFontColor #aaa
skinparam ActivityBorderColor #2D74BA
skinparam ActivityDiamondBorderColor #2D74BA
skinparam ActorBorderColor #2D74BA
skinparam AgentBorderColor #2D74BA
skinparam ArtifactBorderColor #2D74BA
skinparam BoundaryBorderColor #2D74BA
skinparam CardBorderColor #2D74BA
skinparam ClassBorderColor #2D74BA
skinparam CloudBorderColor #2D74BA
skinparam CollectionsBorderColor #2D74BA
skinparam ComponentBorderColor #2D74BA
skinparam ControlBorderColor #2D74BA
skinparam DatabaseBorderColor #2D74BA
skinparam EntityBorderColor #2D74BA
skinparam FileBorderColor #2D74BA
skinparam FolderBorderColor #2D74BA
skinparam FrameBorderColor #2D74BA
skinparam InterfaceBorderColor #2D74BA
skinparam LegendBorderColor #2D74BA
skinparam NodeBorderColor #2D74BA
skinparam NoteBorderColor #2D74BA
skinparam ObjectBorderColor #2D74BA
skinparam PackageBorderColor #2D74BA
skinparam PageBorderColor #2D74BA
skinparam ParticipantBorderColor #2D74BA
skinparam PartitionBorderColor #2D74BA
skinparam QueueBorderColor #2D74BA
skinparam RectangleBorderColor #2D74BA
skinparam SequenceBoxBorderColor #2D74BA
skinparam SequenceDividerBorderColor #2D74BA
skinparam SequenceGroupBorderColor #2D74BA
skinparam SequenceLifeLineBorderColor #2D74BA
skinparam SequenceReferenceBorderColor #2D74BA
skinparam StackBorderColor #2D74BA
skinparam StateBorderColor #2D74BA
skinparam StereotypeABorderColor #2D74BA
skinparam StereotypeCBorderColor #2D74BA
skinparam StereotypeEBorderColor #2D74BA
skinparam StereotypeIBorderColor #2D74BA
skinparam StereotypeNBorderColor #2D74BA
skinparam StorageBorderColor #2D74BA
skinparam SwimlaneBorderColor #2D74BA
skinparam UsecaseBorderColor #2D74BA

skinparam ActivityBackgroundColor #1e2029
skinparam ActivityDiamondBackgroundColor #1e2029
skinparam ActorBackgroundColor #1e2029
skinparam AgentBackgroundColor #1e2029
skinparam ArtifactBackgroundColor #1e2029
skinparam BoundaryBackgroundColor #1e2029
skinparam CardBackgroundColor #1e2029
skinparam ClassBackgroundColor #1e2029
skinparam ClassHeaderBackgroundColor #1e2029
skinparam CloudBackgroundColor #1e2029
skinparam CollectionsBackgroundColor #1e2029
skinparam ComponentBackgroundColor #1e2029
skinparam ControlBackgroundColor #1e2029
skinparam DatabaseBackgroundColor #1e2029
skinparam EntityBackgroundColor #1e2029
skinparam FileBackgroundColor #1e2029
skinparam FolderBackgroundColor #1e2029
skinparam FrameBackgroundColor #1e2029
skinparam IconPackageBackgroundColor #1e2029
skinparam IconPrivateBackgroundColor #1e2029
skinparam IconProtectedBackgroundColor #1e2029
skinparam IconPublicBackgroundColor #1e2029
skinparam InterfaceBackgroundColor #1e2029
skinparam LegendBackgroundColor #1e2029
skinparam NodeBackgroundColor #1e2029
skinparam NoteBackgroundColor #1e2029
skinparam ObjectBackgroundColor #1e2029
skinparam PackageBackgroundColor #1e2029
skinparam ParticipantBackgroundColor #1e2029
skinparam PartitionBackgroundColor #1e2029
skinparam QueueBackgroundColor #1e2029
skinparam RectangleBackgroundColor #1e2029
skinparam SequenceBoxBackgroundColor #1e2029
skinparam SequenceDividerBackgroundColor #1e2029
skinparam SequenceGroupBackgroundColor #1e2029
skinparam SequenceGroupBodyBackgroundColor #1e2029
skinparam SequenceLifeLineBackgroundColor #1e2029
skinparam SequenceReferenceBackgroundColor #1e2029
skinparam SequenceReferenceHeaderBackgroundColor #1e2029
skinparam StackBackgroundColor #1e2029
skinparam StateBackgroundColor #1e2029
skinparam StereotypeABackgroundColor #1e2029
skinparam StereotypeCBackgroundColor #1e2029
skinparam StereotypeEBackgroundColor #1e2029
skinparam StereotypeIBackgroundColor #1e2029
skinparam StereotypeNBackgroundColor #1e2029
skinparam StorageBackgroundColor #1e2029
skinparam TitleBackgroundColor #1e2029
skinparam UsecaseBackgroundColor #1e2029

skinparam ActivityStartColor #454645
skinparam ActivityEndColor #454645
skinparam StateStartColor #454645
skinparam StateEndColor #454645

skinparam shadowing false
skinparam DefaultFontName Arial
skinparam ArrowColor #00b2e2
skinparam DefaultFontColor #aaa

skinparam ActivityBorderColor #2D74BA
skinparam ActivityDiamondBorderColor #2D74BA
skinparam ActorBorderColor #2D74BA
skinparam AgentBorderColor #2D74BA
skinparam ArtifactBorderColor #2D74BA
skinparam BoundaryBorderColor #2D74BA
skinparam CardBorderColor #2D74BA
skinparam ClassBorderColor #2D74BA
skinparam CloudBorderColor #2D74BA
skinparam CollectionsBorderColor #2D74BA
skinparam ComponentBorderColor #2D74BA
skinparam ControlBorderColor #2D74BA
skinparam DatabaseBorderColor #2D74BA
skinparam EntityBorderColor #2D74BA
skinparam FileBorderColor #2D74BA
skinparam FolderBorderColor #2D74BA
skinparam FrameBorderColor #2D74BA
skinparam InterfaceBorderColor #2D74BA
skinparam LegendBorderColor #2D74BA
skinparam NodeBorderColor #2D74BA
skinparam NoteBorderColor #2D74BA
skinparam ObjectBorderColor #2D74BA
skinparam PackageBorderColor #2D74BA
skinparam PageBorderColor #2D74BA
skinparam ParticipantBorderColor #2D74BA
skinparam PartitionBorderColor #2D74BA
skinparam QueueBorderColor #2D74BA
skinparam RectangleBorderColor #2D74BA
skinparam SequenceBoxBorderColor #2D74BA
skinparam SequenceDividerBorderColor #2D74BA
skinparam SequenceGroupBorderColor #2D74BA
skinparam SequenceLifeLineBorderColor #2D74BA
skinparam SequenceReferenceBorderColor #2D74BA
skinparam StackBorderColor #2D74BA
skinparam StateBorderColor #2D74BA
skinparam StereotypeABorderColor #2D74BA
skinparam StereotypeCBorderColor #2D74BA
skinparam StereotypeEBorderColor #2D74BA
skinparam StereotypeIBorderColor #2D74BA
skinparam StereotypeNBorderColor #2D74BA
skinparam StorageBorderColor #2D74BA
skinparam SwimlaneBorderColor #2D74BA
skinparam UsecaseBorderColor #2D74BA

skinparam ActivityBackgroundColor #1e2029
skinparam ActivityDiamondBackgroundColor #1e2029
skinparam ActorBackgroundColor #1e2029
skinparam AgentBackgroundColor #1e2029
skinparam ArtifactBackgroundColor #1e2029
skinparam BoundaryBackgroundColor #1e2029
skinparam CardBackgroundColor #1e2029
skinparam ClassBackgroundColor #1e2029
skinparam ClassHeaderBackgroundColor #1e2029
skinparam CloudBackgroundColor #1e2029
skinparam CollectionsBackgroundColor #1e2029
skinparam ComponentBackgroundColor #1e2029
skinparam ControlBackgroundColor #1e2029
skinparam DatabaseBackgroundColor #1e2029
skinparam EntityBackgroundColor #1e2029
skinparam FileBackgroundColor #1e2029
skinparam FolderBackgroundColor #1e2029
skinparam FrameBackgroundColor #1e2029
skinparam HyperlinkColor #999999
skinparam HyperlinkUnderline false
skinparam IconPackageBackgroundColor #1e2029
skinparam IconPrivateBackgroundColor #1e2029
skinparam IconProtectedBackgroundColor #1e2029
skinparam IconPublicBackgroundColor #1e2029
skinparam InterfaceBackgroundColor #1e2029
skinparam LegendBackgroundColor #1e2029
skinparam NodeBackgroundColor #1e2029
skinparam NoteBackgroundColor #1e2029
skinparam ObjectBackgroundColor #1e2029
skinparam PackageBackgroundColor #1e2029
skinparam ParticipantBackgroundColor #1e2029
skinparam PartitionBackgroundColor #1e2029
skinparam QueueBackgroundColor #1e2029
skinparam RectangleBackgroundColor #1e2029
skinparam SequenceBoxBackgroundColor #1e2029
skinparam SequenceDividerBackgroundColor #1e2029
skinparam SequenceGroupBackgroundColor #1e2029
skinparam SequenceGroupBodyBackgroundColor #1e2029
skinparam SequenceLifeLineBackgroundColor #1e2029
skinparam SequenceReferenceBackgroundColor #1e2029
skinparam SequenceReferenceHeaderBackgroundColor #1e2029
skinparam StackBackgroundColor #1e2029
skinparam StateBackgroundColor #1e2029
skinparam StereotypeABackgroundColor #1e2029
skinparam StereotypeCBackgroundColor #1e2029
skinparam StereotypeEBackgroundColor #1e2029
skinparam StereotypeIBackgroundColor #1e2029
skinparam StereotypeNBackgroundColor #1e2029
skinparam StorageBackgroundColor #1e2029
skinparam TitleBackgroundColor #1e2029
skinparam UsecaseBackgroundColor #1e2029

skinparam ActivityStartColor #454645
skinparam ActivityEndColor #454645
skinparam StateStartColor #454645
skinparam StateEndColor #454645
