@startuml
participant "MainThread" as MainThread
[-[#888888]-> MainThread: 0
MainThread<-[#888888]-]: [[1.json?req{} runit]]
activate MainThread
[-[#888888]-> MainThread: 1e-05
MainThread<-[#888888]-]: [[2.json?req{\n    "name": "joe"\n} say_hello]]
activate MainThread
deactivate MainThread
deactivate MainThread
@enduml